"""Add aemo_spike_test_mode field to prevent automatic restore during manual testing

Revision ID: 08f369cf953c
Revises: 507d3cf230f7
Create Date: 2025-11-12 21:48:28.799823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f369cf953c'
down_revision = '507d3cf230f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aemo_spike_test_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('aemo_spike_test_mode')

    # ### end Alembic commands ###
