"""Add custom TOU schedule models

Revision ID: 23ae28338b34
Revises: 50a9a98d3426
Create Date: 2025-11-07 13:23:35.012530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ae28338b34'
down_revision = '50a9a98d3426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_tou_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('utility', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('daily_charge', sa.Float(), nullable=True),
    sa.Column('monthly_charge', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tou_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('from_month', sa.Integer(), nullable=False),
    sa.Column('to_month', sa.Integer(), nullable=False),
    sa.Column('from_day', sa.Integer(), nullable=False),
    sa.Column('to_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['custom_tou_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tou_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('from_hour', sa.Integer(), nullable=False),
    sa.Column('from_minute', sa.Integer(), nullable=False),
    sa.Column('to_hour', sa.Integer(), nullable=False),
    sa.Column('to_minute', sa.Integer(), nullable=False),
    sa.Column('from_day_of_week', sa.Integer(), nullable=True),
    sa.Column('to_day_of_week', sa.Integer(), nullable=True),
    sa.Column('energy_rate', sa.Float(), nullable=False),
    sa.Column('sell_rate', sa.Float(), nullable=False),
    sa.Column('demand_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['tou_season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tou_period')
    op.drop_table('tou_season')
    op.drop_table('custom_tou_schedule')
    # ### end Alembic commands ###
