"""Add Teslemetry API key support

Revision ID: 3e7d60d7fdd4
Revises: a8e237e12250
Create Date: 2025-10-21 21:08:56.313999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7d60d7fdd4'
down_revision = 'a8e237e12250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teslemetry_api_key_encrypted', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('teslemetry_api_key_encrypted')

    # ### end Alembic commands ###
