"""remove_manual_control_columns

Revision ID: 507d3cf230f7
Revises: 4aabb8144986
Create Date: 2025-11-11 16:48:43.306089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507d3cf230f7'
down_revision = '4aabb8144986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('manual_control_mode')
        batch_op.drop_column('manual_control_end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_control_end_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('manual_control_mode', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
