"""Add sync_enabled field to User model

Revision ID: 50a9a98d3426
Revises: 72df84211c71
Create Date: 2025-10-28 17:11:45.548719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a9a98d3426'
down_revision = '72df84211c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_enabled', sa.Boolean(), nullable=True))

    # Set default value for existing users (sync enabled by default)
    op.execute("UPDATE user SET sync_enabled = 1 WHERE sync_enabled IS NULL")

    # Make the column non-nullable after setting defaults
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('sync_enabled', nullable=False, server_default='1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sync_enabled')

    # ### end Alembic commands ###
