"""Add is_default field to SavedTOUProfile for default tariff selection

Revision ID: 5163a45a6976
Revises: 08f369cf953c
Create Date: 2025-11-12 22:15:24.753374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5163a45a6976'
down_revision = '08f369cf953c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_tou_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_tou_profile', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
