"""Remove Tesla Fleet API fields and keep only Teslemetry

Revision ID: 58e580f3850e
Revises: 9d453fbea5d9
Create Date: 2025-11-08 21:16:19.047776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e580f3850e'
down_revision = '9d453fbea5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tesla_token_expiry')
        batch_op.drop_column('tesla_region')
        batch_op.drop_column('tesla_fleet_public_key')
        batch_op.drop_column('tesla_fleet_private_key_encrypted')
        batch_op.drop_column('tesla_access_token_encrypted')
        batch_op.drop_column('tesla_redirect_uri')
        batch_op.drop_column('app_domain')
        batch_op.drop_column('tesla_refresh_token_encrypted')
        batch_op.drop_column('tesla_client_secret_encrypted')
        batch_op.drop_column('tesla_client_id_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tesla_client_id_encrypted', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('tesla_client_secret_encrypted', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('tesla_refresh_token_encrypted', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('app_domain', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('tesla_redirect_uri', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('tesla_access_token_encrypted', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('tesla_fleet_private_key_encrypted', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('tesla_fleet_public_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tesla_region', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('tesla_token_expiry', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
