"""Add demand charge configuration fields

Revision ID: 5eddd11699e3
Revises: deb03cb802cd
Create Date: 2025-10-22 22:47:51.589865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eddd11699e3'
down_revision = 'deb03cb802cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_demand_charges', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('peak_demand_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('peak_start_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peak_start_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peak_end_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peak_end_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peak_days', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('offpeak_demand_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shoulder_demand_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shoulder_start_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shoulder_start_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shoulder_end_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shoulder_end_minute', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shoulder_end_minute')
        batch_op.drop_column('shoulder_end_hour')
        batch_op.drop_column('shoulder_start_minute')
        batch_op.drop_column('shoulder_start_hour')
        batch_op.drop_column('shoulder_demand_rate')
        batch_op.drop_column('offpeak_demand_rate')
        batch_op.drop_column('peak_days')
        batch_op.drop_column('peak_end_minute')
        batch_op.drop_column('peak_end_hour')
        batch_op.drop_column('peak_start_minute')
        batch_op.drop_column('peak_start_hour')
        batch_op.drop_column('peak_demand_rate')
        batch_op.drop_column('enable_demand_charges')

    # ### end Alembic commands ###
