"""Add demand_charge_apply_to column to user table

Revision ID: 701c30007885
Revises: 5163a45a6976
Create Date: 2025-11-21 20:47:33.759347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701c30007885'
down_revision = '5163a45a6976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demand_charge_apply_to', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('demand_charge_apply_to')

    # ### end Alembic commands ###
