"""Initial migration for SQLite

Revision ID: 7eaa9113ee3f
Revises: 
Create Date: 2025-10-21 19:35:39.420730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eaa9113ee3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('amber_api_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('tesla_energy_site_id', sa.String(length=50), nullable=True),
    sa.Column('tesla_access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('tesla_refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('tesla_token_expiry', sa.Integer(), nullable=True),
    sa.Column('last_update_status', sa.String(length=255), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
