"""Add aemo_pre_spike_operation_mode field to user table

Revision ID: 888d4f9ca20c
Revises: 701c30007885
Create Date: 2025-11-21 21:10:54.781364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888d4f9ca20c'
down_revision = '701c30007885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aemo_pre_spike_operation_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('aemo_pre_spike_operation_mode')

    # ### end Alembic commands ###
