"""Add tesla_region field for Fleet API region auto-detection

Revision ID: 915ff17b1cec
Revises: fdb3f530544d
Create Date: 2025-10-24 23:59:33.521363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915ff17b1cec'
down_revision = 'fdb3f530544d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tesla_region', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tesla_region')

    # ### end Alembic commands ###
