"""Add EnergyRecord model for usage logging

Revision ID: 92b124cdf79b
Revises: 915ff17b1cec
Create Date: 2025-10-26 20:32:12.626116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b124cdf79b'
down_revision = '915ff17b1cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('solar_power', sa.Float(), nullable=True),
    sa.Column('battery_power', sa.Float(), nullable=True),
    sa.Column('grid_power', sa.Float(), nullable=True),
    sa.Column('load_power', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_record_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_record_timestamp'))

    op.drop_table('energy_record')
    # ### end Alembic commands ###
