"""Add SavedTOUProfile model for backing up and restoring Tesla tariffs

Revision ID: 9d453fbea5d9
Revises: 23ae28338b34
Create Date: 2025-11-08 21:00:10.557223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d453fbea5d9'
down_revision = '23ae28338b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_tou_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('tariff_name', sa.String(length=200), nullable=True),
    sa.Column('utility', sa.String(length=100), nullable=True),
    sa.Column('tariff_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_from_tesla_at', sa.DateTime(), nullable=True),
    sa.Column('last_restored_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_tou_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_tou_profile_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_tou_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_tou_profile_created_at'))

    op.drop_table('saved_tou_profile')
    # ### end Alembic commands ###
