"""Add PriceRecord model for tracking Amber pricing

Revision ID: a8e237e12250
Revises: 7eaa9113ee3f
Create Date: 2025-10-21 20:42:44.812261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e237e12250'
down_revision = '7eaa9113ee3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('per_kwh', sa.Float(), nullable=True),
    sa.Column('spot_per_kwh', sa.Float(), nullable=True),
    sa.Column('wholesale_kwh_price', sa.Float(), nullable=True),
    sa.Column('network_kwh_price', sa.Float(), nullable=True),
    sa.Column('market_kwh_price', sa.Float(), nullable=True),
    sa.Column('green_kwh_price', sa.Float(), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=True),
    sa.Column('forecast', sa.Boolean(), nullable=True),
    sa.Column('nem_time', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('spike_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_record_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_record_timestamp'))

    op.drop_table('price_record')
    # ### end Alembic commands ###
