"""Add Tesla Fleet API virtual key fields

Revision ID: deb03cb802cd
Revises: 1761dc78f042
Create Date: 2025-10-22 17:23:16.531421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb03cb802cd'
down_revision = '1761dc78f042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tesla_fleet_private_key_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('tesla_fleet_public_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tesla_fleet_public_key')
        batch_op.drop_column('tesla_fleet_private_key_encrypted')

    # ### end Alembic commands ###
