"""Add Amber forecast type and 30min shift settings

Revision ID: e23c3eecc9a3
Revises: fe748f5a4c8d
Create Date: 2025-11-10 20:40:31.345944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23c3eecc9a3'
down_revision = 'fe748f5a4c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amber_forecast_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('amber_30min_shift_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('amber_30min_shift_enabled')
        batch_op.drop_column('amber_forecast_type')

    # ### end Alembic commands ###
