"""Add Tesla OAuth credentials to User model

Revision ID: fdb3f530544d
Revises: 5eddd11699e3
Create Date: 2025-10-24 23:05:25.236121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb3f530544d'
down_revision = '5eddd11699e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tesla_client_id_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('tesla_client_secret_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('tesla_redirect_uri', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('app_domain', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('app_domain')
        batch_op.drop_column('tesla_redirect_uri')
        batch_op.drop_column('tesla_client_secret_encrypted')
        batch_op.drop_column('tesla_client_id_encrypted')

    # ### end Alembic commands ###
