"""Add AEMO spike detection configuration fields

Revision ID: fe748f5a4c8d
Revises: 58e580f3850e
Create Date: 2025-11-08 21:59:45.561466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe748f5a4c8d'
down_revision = '58e580f3850e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aemo_region', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('aemo_spike_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aemo_spike_detection_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aemo_in_spike_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aemo_last_check', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aemo_last_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aemo_spike_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aemo_saved_tariff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_aemo_saved_tariff', 'saved_tou_profile', ['aemo_saved_tariff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_aemo_saved_tariff', type_='foreignkey')
        batch_op.drop_column('aemo_saved_tariff_id')
        batch_op.drop_column('aemo_spike_start_time')
        batch_op.drop_column('aemo_last_price')
        batch_op.drop_column('aemo_last_check')
        batch_op.drop_column('aemo_in_spike_mode')
        batch_op.drop_column('aemo_spike_detection_enabled')
        batch_op.drop_column('aemo_spike_threshold')
        batch_op.drop_column('aemo_region')

    # ### end Alembic commands ###
